name: POWHEG_PYTHIA6_DIJET_BORNKT05_BORNSUPP20_13TeV
numevents: 25000
numbjobs: 1600
gen: powheg+pythia6
proc: dijet
lhans: 11000
beam_type: pp
ebeam1: 6500
ebeam2: 6500
add_d_mesons: no
extended_event_info: yes
powheg_config:
  bornktmin: 0.5
  bornsuppfact: 20
grid_config:
  ttl: 80000
  max_files_per_job: 20
  aliphysics: vAN-20190317-1
