name: HERWIG_MB_13TeV
numevents: 50000
numbjobs: 400
gen: herwig
proc: mb
beam_type: pp
lhans: 10550
ebeam1: 6500
ebeam2: 6500
add_d_mesons: yes
extended_event_info: yes
grid_config:
  load_packages_separately: yes
  ttl: 50000
  max_files_per_job: 20
  aliphysics: vAN-20190314_ROOT6-1
